name: Test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --requirement binder/requirements.txt
        python -m pip install --requirement book/requirements.txt
        python -m pip install --upgrade --requirement dev-requirements.txt

    - name: List installed dependencies
      run: python -m pip list

    - name: Test with pytest
      run: |
        pytest --ignore tests/test_notebooks.py
